# This is a sample docker-compose.yml file that constructs
# a Docker environment for Rails development.
version: "3.7"
services:
  rails:
    build:
      context: .
      args:
        PUBLIC_KEY: "docker.pub"
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ${DORA_HOST_APP_DIR}:/home/dora/rails/
    environment:
      # By omitting the values, the variables are taken
      # from the current environment. This requires an
      # existing `.env` file (or any other means of
      # setting the variables).
      - APP_NAME
      - DORA_HOST_APP_DIR
      - DORA_HOST_VOL_DIR
      - EMAIL_REPORTS_TO
      - GIT_PULL
      - PASSENGER_APP_ENV
      - RAILS_PRECOMPILE_ASSETS
      - RAILS_DB_HOST
      - RAILS_DB_NAME
      - RAILS_DB_USER
      - RAILS_DB_PASS
      - RAILS_SMTP_HOST
      - RAILS_SMTP_PORT
      - RAILS_SMTP_USER
      - RAILS_SMTP_PASS
      - RAILS_SMTP_FROM
      - TIMEZONE
      - WEBHOOK_SECRET
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - ${DORA_HOST_VOL_DIR}/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer:4.7
    ports:
      - "127.0.0.1:3001:8080"
    depends_on:
      - db
  redis:
    image: redis
  selenium:
    image: selenium/standalone-firefox:3.141.59-zirconium
    environment:
      START_XVFB: "false"
    volumes:
      - /dev/shm:/dev/shm
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      # Expose the UI's port on the host, but do not expose it to the world.
      # MailHog's SMTP port 1025 is not listed here because it needs to be
      # available on the Docker network only.
      - "127.0.0.1:8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog/maildir
    volumes:
      - ${DORA_HOST_VOL_DIR}/mailhog:/home/mailhog/maildir
